# Generated by Django 5.0.6 on 2024-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='catg_image',
            field=models.ImageField(blank=True, null=True, upload_to='Category Images'),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='catg_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
