# Generated by Django 5.0.6 on 2024-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyApp', '0002_categorydb_catg_image_alter_categorydb_catg_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Service_price', models.IntegerField(blank=True, null=True)),
                ('Service_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('Service_image', models.ImageField(blank=True, null=True, upload_to='Service Images')),
            ],
        ),
    ]
