# Generated by Django 5.0.6 on 2024-06-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyApp', '0003_servicedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedb',
            name='Service_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
