# Generated by Django 5.0.6 on 2024-06-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyApp', '0004_alter_servicedb_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairservicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Haircat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Hair_category', models.CharField(blank=True, max_length=100, null=True)),
                ('Hair_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Hair_price', models.CharField(blank=True, max_length=100, null=True)),
                ('Hair_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('Hair_image', models.ImageField(blank=True, null=True, upload_to='Service Images')),
            ],
        ),
    ]
