# Generated by Django 5.0.6 on 2024-06-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyApp', '0005_hairservicedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairservicedb',
            name='Hair_image',
            field=models.ImageField(blank=True, null=True, upload_to='Hair Images'),
        ),
    ]
