# Generated by Django 5.0.6 on 2024-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyApp', '0006_alter_hairservicedb_hair_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skinservicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skincat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Skin_category', models.CharField(blank=True, max_length=100, null=True)),
                ('Skin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Skin_price', models.CharField(blank=True, max_length=100, null=True)),
                ('Skin_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('Skin_image', models.ImageField(blank=True, null=True, upload_to='Skin Images')),
            ],
        ),
    ]
