# Generated by Django 5.0.6 on 2024-06-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyApp', '0007_skinservicedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nailservicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nailcat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Nail_category', models.CharField(blank=True, max_length=100, null=True)),
                ('Nail_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Nail_price', models.CharField(blank=True, max_length=100, null=True)),
                ('Nail_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('Nail_image', models.ImageField(blank=True, null=True, upload_to='Nail Images')),
            ],
        ),
    ]
