# Generated by Django 5.0.6 on 2024-06-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyApp', '0008_nailservicedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makeupservicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Makeupcat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Makeup_category', models.CharField(blank=True, max_length=100, null=True)),
                ('Makeup_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Makeup_price', models.CharField(blank=True, max_length=100, null=True)),
                ('Makeup_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('Makeup_image', models.ImageField(blank=True, null=True, upload_to='Makeup Images')),
            ],
        ),
    ]
