# Generated by Django 5.0.6 on 2024-08-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyApp', '0010_bodycareservicedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_username', models.CharField(blank=True, max_length=100, null=True)),
                ('cart_productname', models.CharField(blank=True, max_length=100, null=True)),
                ('cart_qty', models.IntegerField(blank=True, null=True)),
                ('cart_totalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
