# Generated by Django 5.0.6 on 2024-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_name', models.CharField(blank=True, max_length=100, null=True)),
                ('signup_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('signup_pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('signup_cpwd', models.CharField(blank=True, max_length=100, null=True)),
                ('signup_mail', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
