# Generated by Django 5.0.6 on 2024-07-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_signupdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='signup_lastname',
        ),
    ]
