# Generated by Django 5.0.6 on 2024-07-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_signupdb_signup_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_user', models.CharField(blank=True, max_length=100, null=True)),
                ('book_mail', models.EmailField(blank=True, max_length=100, null=True)),
                ('book_mob', models.IntegerField(blank=True, max_length=100, null=True)),
                ('book_service', models.CharField(blank=True, max_length=100, null=True)),
                ('book_date', models.DateField(blank=True, max_length=100, null=True)),
                ('book_time', models.TimeField()),
            ],
        ),
    ]
