# Generated by Django 5.0.6 on 2024-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_bookdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.CharField(blank=True, max_length=100, null=True)),
                ('app_mail', models.EmailField(blank=True, max_length=100, null=True)),
                ('app_mob', models.IntegerField(blank=True, max_length=100, null=True)),
                ('app_place', models.IntegerField(blank=True, max_length=100, null=True)),
                ('app_enquiry', models.TextField(blank=True, max_length=100, null=True)),
                ('app_date', models.DateField(blank=True, max_length=100, null=True)),
                ('app_time', models.TimeField()),
            ],
        ),
    ]
