# Generated by Django 5.0.6 on 2024-07-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_appointmentdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='book_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookdb',
            name='book_sername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
